### PR TITLE
Release v2.1.1.1

### PR DESCRIPTION
**Pull request by IshaanDesai**
Release PR for preCICE release v.2.1.1

### CODE REVIEW

**Review by BenjaminRueth — CHANGES_REQUESTED** [review]
There is not much to review here, since this PR/verison only ensures compatibility with preCICE `v2.1.1`. However, a completely empty PR looks strange to me. See #24.

Please also make sure to [draft a release](https://github.com/precice/matlab-bindings/releases/new) for the MATLAB bindings.

**Comment by BenjaminRueth** [comment]
Note that for these kind of "compatibility releases" in the python bindings, we do not even have a PR (e.g. [`v2.0.2.1`](https://github.com/precice/python-bindings/compare/v2.0.1.1...v2.0.2.1) is missing [here](https://github.com/precice/python-bindings/pulls?q=is%3Apr+is%3Aclosed)), but there is always at least one changing commit (for `v2.0.2.1` https://github.com/precice/python-bindings/commit/18fac1f27189cb4f8baa33de1578b902753611f3).

The release process for the python bindings is not fully converged, either, but my gut feeling tells me that we should at least have a `Bump version` commit for each release. Solving #24 would be ideal, but for now we could just add a short note to the `README.md`.

Whether we really need a PR, if it is only about bumping the version, I am unsure. This might also be a bit of over-engineering. But we should always have a [release](https://github.com/precice/matlab-bindings/releases) and a [tag](https://github.com/precice/matlab-bindings/tags).

**Comment by IshaanDesai** [comment]
The following basic steps seem reasonable for a minimal compatibility release:
  1. Commit `Bump version` to `develop`
  2. Open PR from `develop` --> `master`
  3. Draft a release
  4. Release new package and merge PR into `master`

* The [draft release](https://github.com/precice/matlab-bindings/releases/tag/untagged-9fc92b4a3271288062b7) has been made.
* For now adding the version in the README is okay I think.

**Comment by fsimonis** [comment]
From my experience of releasing precice, I can highly recommend to use release branches.

This sounds totally overengineered, but it is in fact easier to handle than merging straight from develop to master.
Main upside is that you can bump and test the version in isolation. Reverting changes on develop is very ugly and force pushing the primary branch of your repository would be ... brave. 

For the python bindings, the procedure could looks as follows.
This may seem frightening, but it is actually just a lot of switching and updating branches.
* git switch develop
* git pull
* git checkout -b v2.1.1.1
* bump version and commit 
* git push v2.1.1.1
* open pr from release branch to master
* test the branch on various systems
* merge pr (no rebase, fast-forward or squash) you can also follow the command line instructions right next to the merge button
* tag last commit on master. You can use the github release window for that. 
* git switch master
* git pull
* git switch develop
* git pull
* git merge --no-ff master
* git describe --tags
* git push

I am not sure how we can end up in a situation where a release has no commits. The version of the bindings are strictly tied to the precice version. The version changes even if there is a new release candidate.

**Review by BenjaminRueth — APPROVED** [review]
Thanks to #25 we now have a diff (and will also have one in the future).

**Pull request merged**
